development:
  adapter: postgresql
  database: pentest
  username: pentest
  password: pentest
  host: postgres
  port: 5432
  pool: 5
  timeout: 5

production:
  adapter: postgresql
  database: pentest
  username: pentest
  password: pentest
  host: postgres 
  port: 5432
  pool: 5
  timeout: 5

test:
  adapter: postgresql
  database: pentest_test
  username: pentest
  password: pentest
  host: postgres
  port: 5432
  pool: 5
  timeout: 5